import { createFileRoute } from "@tanstack/react-router";
import { useDeferredValue, useMemo, useState } from "react";
import { AppShell } from "@/components/app/AppShell";
import { PageHeader } from "@/components/app/ui-kit";
import { BookOpen, Bookmark, Check, Clock3, Download, FileText, Filter, History, LibraryBig, Play, Search, Send, Star, Upload, X } from "lucide-react";

export const Route = createFileRoute("/library")({
  head: () => ({ meta: [{ title: "University library — Student TM" }, { name: "description", content: "Books, journals and digital resources for university study." }] }),
  component: LibraryPage,
});

type Resource = { id: number; title: string; author: string; type: string; format: string; category: string; faculty: string; year: number; available: boolean; rating: number; views: number; color: string; description: string };
const resources: Resource[] = [
  { id: 1, title: "Introduction to Algorithms", author: "T. Cormen, C. Leiserson", type: "Книга", format: "PDF", category: "IT и технологии", faculty: "Инженерия", year: 2024, available: true, rating: 4.9, views: 842, color: "from-blue-500 to-cyan-400", description: "Базовый курс алгоритмов, структур данных и анализа сложности." },
  { id: 2, title: "Academic Writing Guide", author: "University Press", type: "Пособие", format: "DOCX", category: "Языки", faculty: "Гуманитарные науки", year: 2023, available: true, rating: 4.7, views: 624, color: "from-violet-500 to-fuchsia-400", description: "Практическое руководство по исследовательским и академическим текстам." },
  { id: 3, title: "Modern Microeconomics", author: "A. Mas-Colell", type: "Книга", format: "PDF", category: "Экономика", faculty: "Экономика", year: 2022, available: false, rating: 4.8, views: 510, color: "from-amber-500 to-orange-400", description: "Современный взгляд на модели и методы микроэкономики." },
  { id: 4, title: "Data Structures & Patterns", author: "R. Sedgewick", type: "Электронная книга", format: "Видео", category: "IT и технологии", faculty: "Инженерия", year: 2024, available: true, rating: 4.9, views: 936, color: "from-emerald-500 to-teal-400", description: "Серия лекций о проектировании надёжных программных систем." },
];
const categories = ["Все", "IT и технологии", "Языки", "Экономика"];

function LibraryPage() {
  const [query, setQuery] = useState("");
  const deferredQuery = useDeferredValue(query);
  const [category, setCategory] = useState("Все");
  const [faculty, setFaculty] = useState("Все факультеты");
  const [format, setFormat] = useState("Все форматы");
  const [sort, setSort] = useState("Популярность");
  const [saved, setSaved] = useState<number[]>([2]);
  const [history, setHistory] = useState<number[]>([4]);
  const [preview, setPreview] = useState<Resource | null>(null);
  const [notice, setNotice] = useState("");
  const [rating, setRating] = useState(0);

  const filtered = useMemo(() => resources.filter((item) => {
    const text = `${item.title} ${item.author}`.toLowerCase();
    return text.includes(deferredQuery.toLowerCase()) && (category === "Все" || item.category === category) && (faculty === "Все факультеты" || item.faculty === faculty) && (format === "Все форматы" || item.format === format);
  }).sort((a, b) => sort === "Название" ? a.title.localeCompare(b.title) : sort === "Новизна" ? b.year - a.year : b.views - a.views), [deferredQuery, category, faculty, format, sort]);

  const toggleSaved = (id: number) => setSaved((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]);
  const openPreview = (item: Resource) => { setPreview(item); setHistory((items) => [item.id, ...items.filter((id) => id !== item.id)]); };
  const flash = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 2600); };

  return <AppShell allow={["student", "teacher"]}>
    <div className="space-y-5">
      <PageHeader title="Библиотека" description="Знания всегда рядом" />
      <section className="relative overflow-hidden rounded-[1.75rem] bg-gradient-to-br from-primary via-primary to-indigo-500 p-5 text-primary-foreground shadow-lg shadow-primary/20">
        <div aria-hidden="true" className="absolute -right-10 -top-10 h-36 w-36 rounded-full bg-white/10 opacity-70" />
        <div className="relative flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary-foreground/70">Университетская коллекция</p><h2 className="mt-2 max-w-[300px] text-2xl font-extrabold leading-tight">Найди свою следующую идею</h2><p className="mt-2 text-sm text-primary-foreground/75">12 480 книг и материалов для учёбы</p></div><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-white/15 backdrop-blur-sm"><LibraryBig className="h-7 w-7" /></div></div>
        <div className="relative mt-5 flex items-center gap-2 rounded-2xl bg-white p-1.5 text-foreground shadow-xl"><Search className="ml-2 h-4 w-4 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Поиск книг, авторов..." className="min-w-0 flex-1 bg-transparent px-1 py-2 text-sm outline-none placeholder:text-muted-foreground" aria-label="Поиск в библиотеке" /><kbd className="mr-2 hidden rounded-md bg-muted px-2 py-1 text-[10px] text-muted-foreground sm:block">⌘ K</kbd></div>
      </section>
      <div className="flex gap-2 overflow-x-auto pb-1 [scrollbar-width:none]">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-semibold transition ${category === item ? "bg-foreground text-background" : "border border-border bg-card text-muted-foreground"}`}>{item}</button>)}<button onClick={() => document.getElementById("library-filters")?.classList.toggle("hidden")} className="ml-auto flex shrink-0 items-center gap-1 rounded-full border border-border px-3 py-2 text-xs font-semibold text-muted-foreground"><Filter className="h-3.5 w-3.5" /> Фильтры</button></div>
      <div id="library-filters" className="hidden grid gap-2 rounded-2xl border border-border bg-card p-3 sm:grid-cols-3"><label className="text-xs font-semibold">Факультет<select value={faculty} onChange={(e) => setFaculty(e.target.value)} className="mt-1 w-full rounded-xl border border-border bg-background p-2 text-sm font-normal"><option>Все факультеты</option><option>Инженерия</option><option>Экономика</option><option>Гуманитарные науки</option></select></label><label className="text-xs font-semibold">Формат<select value={format} onChange={(e) => setFormat(e.target.value)} className="mt-1 w-full rounded-xl border border-border bg-background p-2 text-sm font-normal"><option>Все форматы</option><option>PDF</option><option>DOCX</option><option>Видео</option></select></label><label className="text-xs font-semibold">Сортировка<select value={sort} onChange={(e) => setSort(e.target.value)} className="mt-1 w-full rounded-xl border border-border bg-background p-2 text-sm font-normal"><option>Популярность</option><option>Новизна</option><option>Название</option></select></label></div>
      <div className="grid gap-5 lg:grid-cols-[1fr_280px]"><section><div className="mb-3 flex items-center justify-between"><h2 className="font-bold">Рекомендуем вам</h2><span className="text-xs text-muted-foreground">{filtered.length} результата</span></div><div className="content-auto grid gap-3 sm:grid-cols-2">{filtered.map((item) => <article key={item.id} className="group rounded-2xl border border-border bg-card p-3 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><button onClick={() => openPreview(item)} className={`relative flex h-28 w-full items-end overflow-hidden rounded-xl bg-gradient-to-br ${item.color} p-3 text-left text-white`}><div className="absolute right-3 top-3 flex h-8 w-8 items-center justify-center rounded-full bg-black/15 backdrop-blur-sm">{item.format === "Видео" ? <Play className="h-4 w-4" /> : <BookOpen className="h-4 w-4" />}</div><span className="relative max-w-[80%] text-sm font-bold leading-tight">{item.title}</span></button><div className="pt-3"><div className="flex items-start justify-between gap-2"><div><h3 className="text-sm font-bold leading-tight">{item.title}</h3><p className="mt-1 text-xs text-muted-foreground">{item.author}</p></div><button onClick={() => toggleSaved(item.id)} aria-label="Добавить в закладки" className={`rounded-lg p-1.5 ${saved.includes(item.id) ? "text-primary" : "text-muted-foreground"}`}><Bookmark className={`h-4 w-4 ${saved.includes(item.id) ? "fill-current" : ""}`} /></button></div><div className="mt-3 flex items-center justify-between text-[11px] text-muted-foreground"><span className="flex items-center gap-1"><Star className="h-3 w-3 fill-amber-400 text-amber-400" /> {item.rating}</span><span>{item.format} · {item.year} · {item.views} просмотров</span></div><button onClick={() => openPreview(item)} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl bg-primary py-2.5 text-xs font-bold text-primary-foreground transition hover:bg-primary/90"><FileText className="h-3.5 w-3.5" /> Предпросмотр</button></div></article>)}</div>{filtered.length === 0 && <div className="rounded-2xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">Ничего не найдено. Попробуйте изменить фильтры.</div>}</section>
        <aside className="space-y-3"><div className="rounded-2xl border border-border bg-card p-4"><div className="flex items-center gap-2"><History className="h-4 w-4 text-primary" /><h2 className="text-sm font-bold">Продолжить чтение</h2></div><div className="mt-3 space-y-2">{history.slice(0, 2).map((id) => { const item = resources.find((resource) => resource.id === id); return item && <button key={id} onClick={() => openPreview(item)} className="flex w-full items-center gap-2 rounded-xl bg-muted/50 p-2 text-left"><div className={`h-9 w-9 rounded-lg bg-gradient-to-br ${item.color}`} /><span className="min-w-0 text-xs font-semibold truncate">{item.title}<span className="block text-[10px] font-normal text-muted-foreground">Открыть снова</span></span></button>; })}</div></div><div className="rounded-2xl border border-border bg-card p-4"><h2 className="text-sm font-bold">Мои книги</h2><p className="mt-1 text-xs text-muted-foreground">{saved.length} в закладках</p><button onClick={() => flash("Список закладок обновлён")} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-border py-2 text-xs font-semibold"><Bookmark className="h-3.5 w-3.5" /> Открыть закладки</button></div><button onClick={() => flash("Файл добавлен на модерацию")} className="flex w-full items-center justify-center gap-2 rounded-2xl border border-dashed border-primary/40 bg-primary/5 p-4 text-xs font-bold text-primary"><Upload className="h-4 w-4" /> Предложить материал</button></aside></div>
      {notice && <div className="fixed bottom-5 left-1/2 z-30 flex -translate-x-1/2 items-center gap-2 rounded-full bg-foreground px-4 py-3 text-xs font-semibold text-background shadow-xl"><Check className="h-4 w-4 text-emerald-400" />{notice}</div>}
      {preview && <div className="fixed inset-0 z-40 flex items-end justify-center bg-black/60 p-0 backdrop-blur-sm sm:items-center sm:p-4" role="dialog" aria-modal="true"><div className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-t-3xl border border-border bg-card p-5 shadow-2xl sm:rounded-3xl"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-widest text-primary">{preview.format} · {preview.year}</p><h2 className="mt-1 text-xl font-bold">{preview.title}</h2><p className="text-sm text-muted-foreground">{preview.author}</p></div><button onClick={() => setPreview(null)} aria-label="Закрыть предпросмотр" className="rounded-full p-2 hover:bg-muted"><X className="h-5 w-5" /></button></div><div className={`mt-5 flex h-48 items-center justify-center rounded-2xl bg-gradient-to-br ${preview.color} text-white`}>{preview.format === "Видео" ? <Play className="h-12 w-12" /> : <div className="text-center"><FileText className="mx-auto h-12 w-12" /><p className="mt-2 text-xs font-semibold">Предпросмотр документа</p></div>}</div><p className="mt-4 text-sm text-muted-foreground">{preview.description}</p><div className="mt-4 flex items-center gap-1">{[1,2,3,4,5].map((value) => <button key={value} onClick={() => setRating(value)} aria-label={`Оценка ${value}`}><Star className={`h-5 w-5 ${value <= rating ? "fill-amber-400 text-amber-400" : "text-muted-foreground"}`} /></button>)}<span className="ml-2 text-xs text-muted-foreground">Оставьте оценку</span></div><div className="mt-5 flex gap-2"><button onClick={() => flash("Материал добавлен в загрузки")} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-primary py-3 text-xs font-bold text-primary-foreground"><Download className="h-4 w-4" /> Скачать</button><button onClick={() => flash("Жалоба отправлена модератору")} className="flex items-center gap-2 rounded-xl border border-border px-4 py-3 text-xs font-semibold"><Send className="h-4 w-4" /> Пожаловаться</button></div></div></div>}
    </div>
  </AppShell>;
}
